### ISSUE TITLE
Only show "Last updated" info if it was updated longer than x minutes ago

### ISSUE THREAD

**Issue by Maximus97** [hasl-sensor/lovelace-hasl-departure-card#12]
With this card working very well and rarely encountering issues, I have stopped looking at the "Last updated" text. I believe this is the case for many others since the text only changes one digit depending on if it was updated 0 minutes or 8 minutes ago.

Because of this reason, I think the updated text only should appear if the last update was more than x minutes ago (this number would be configurable in config, I personally would set it to 0).

**Comment by dimmanramone** [comment]
@Maximus97 Can you post both the sensor and you card configuration?

**Comment by Maximus97** [comment]
```
sensor:
- platform: hasl
  ri4key: -
  si2key: -
  tl2key: -
  sensors:
   - friendly_name: -
     sensor_type: departures
     siteid: -
     scan_interval: 30
     direction: 2
     timewindow : 60
   - friendly_name: -
     sensor_type: departures
     siteid: -
     lines: -
     scan_interval: 30
     timewindow : 60
     direction: 1
   - friendly_name: Trafikstatus
     sensor_type: status
     scan_interval: 60

type: vertical-stack
cards:
  - adjust_times: false
    compact: true
    departures: true
    deviations: true
    entities:
      - -
    header: false
    hide_departed: true
    language: sv-SV
    name: -
    timeleft: false
    type: 'custom:hasl-departure-card'
    updated: true
  - adjust_times: false
    compact: true
    departures: true
    deviations: true
    entities:
      - -
    header: false
    hide_departed: true
    language: sv-SV
    name: -
    timeleft: false
    type: 'custom:hasl-departure-card'
    updated: true
```

I replaced personalized information and keys with -
