### ISSUE TITLE
NaN in Avgång

### ISSUE THREAD

**Issue by fatuuse** [hasl-sensor/lovelace-hasl-departure-card#23]
In the departure box I get NaN for leaving in x minutes 
![Screenshot_20230114-102610](https://user-images.githubusercontent.com/26528052/212465324-9da3bfc3-8632-47b9-bb04-d9bfaf3b9db8.png)

attributes in sensor for station:
```
unit_of_measurement: min
api_result: Ok
scan_interval: 300
refresh_enabled: false
attribution: Stockholms Lokaltrafik
departures:
  - line: '474'
    direction: 1
    departure: 6 min
    destination: Hemmesta
    time: 6
    expected: '2023-01-14T10:22:00'
    type: Buses
    groupofline: blåbuss
    icon: mdi:bus
deviations: []
last_refresh: '2023-01-14 10:15:24'
next_departure_minutes: 0
next_departure_time: '10:30:18'
deviation_count: 0
icon: mdi:train
friendly_name: Slussen
```

Departure card: 2.6.0
Swedish Public Transport Sensor (HASL): 3.1.0
HASS: 2023.1.4
